services:
  website:
    image: nginx:latest
    container_name: website
    volumes:
      - "C:\\Users\\anilr\\Desktop\\testserver:/usr/share/nginx/html"
    ports:
      - "80:80"
    restart: always